### ISSUE TITLE
Please elaborate README + Screenshots

### ISSUE THREAD

**Issue by luzpaz** [maidenone/RobotCreator#1]
When the time is right. Also add the FreeCAD forum thread users can use for discussion. Thx!

**Comment by maidenone** [comment]
Sure will do, when I have something that work, right now its just an empty workspace with two scripts, 1. export mesh as .stl scaled to meters, then another script that puts origo of the model at the center of mass.

I will add:

- generation of .sdf
- generation of .world (gazebo)
- launch of gazebo 
- joint control in gazebo from FreeCAD
- Add joint dummy object

Also the name is not that great, might be confused with the Robotic Workbench. But the "URDF or SDF" workbench is not entirely correct either, and  "Gazebo workbench" is also not entirely correct.

Forum thread:
https://forum.freecadweb.org/viewtopic.php?f=10&t=15442
