### ISSUE TITLE
Road widget is not shown

### ISSUE THREAD

**Issue by maidenone** [maidenone/RobotCreator#18]
![image](https://github.com/maidenone/RobotDescriptor/assets/1190224/3c92f920-3435-470c-bc1d-780e565de707)
When pressing init then sdf world stuff the road tab is not rendered.

**Comment by Jsevenh** [comment]
Any errors printed   to the console ?

**Comment by maidenone** [comment]
nope, are tring to find out more, are putting print traces everywhere ;)

**Comment by Jsevenh** [comment]
can You try opening the  world--.ui file from your machine see if the  widgets on  that tab have issues

**Comment by maidenone** [comment]
hehe, found my issue, hade copied instead of created symlinks to .local/share/FreeCAD/Mod so had old files there not the up to date files or the files i tried to make changes to.
